export const MOVIES = [
  {
    title: 'Avengers',
    genres: ['Fantasy'],
    year: 2022,
    posterurl: '../assets/poster.webp',
    id: 1,
  },
  {
    title: 'Avengers',
    genres: ['Fantasy'],
    year: 2022,
    posterurl: '../assets/poster.webp',
    id: 2,
  },
  {
    title: 'Avengers',
    genres: ['Fantasy'],
    year: 2022,
    posterurl: '../assets/poster.webp',
    id: 3,
  },
  {
    title: 'Avengers',
    genres: ['Fantasy'],
    year: 2022,
    posterurl: '../assets/poster.webp',
    id: 4,
  },
  {
    title: 'Avengers',
    genres: ['Fantasy'],
    year: 2022,
    posterurl: '../assets/poster.webp',
    id: 5,
  },
  {
    title: 'Avengers',
    genres: ['Fantasy'],
    year: 2022,
    posterurl: '../assets/poster.webp',
    id: 6,
  },
  {
    title: 'Avengers',
    genres: ['Fantasy'],
    year: 2022,
    posterurl: '../assets/poster.webp',
    id: 7,
  },
  {
    title: 'Avengers',
    genres: ['Fantasy'],
    year: 2022,
    posterurl: '../assets/poster.webp',
    id: 8,
  },
  {
    title: 'Avengers',
    genres: ['Fantasy'],
    year: 2022,
    posterurl: '../assets/poster.webp',
    id: 9,
  },
];
